
  php-{project}:
    restart: always
    build: docker/image/php
    ports:
      - {port}:80
      - {port-ssl}:443
    volumes:
      - "./src:/var/www/html"
      - "./logs/apache:/var/log/apache2"
