
  #PHP Service
  ci4-app-{project}:
    build: docker/image/php
    container_name: ci4-app-{project}
    restart: unless-stopped
    tty: true
    environment:
      #SERVICE_NAME: app
      #SERVICE_TAGS: dev
      PHP_IDE_CONFIG: serverName={project}
    links:
      - mysql-{project}:db-server
    volumes:
      - ./src:/var/www
      #- ./docker/image/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      #- ./docker/image/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      #- ./docker/image/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - app-network-ci4-{project}

  #Nginx Service
  ci4-nginx-{project}:
    image: nginx:alpine
    container_name: ci4-nginx-{project}
    restart: unless-stopped
    tty: true
    ports:
      - "{port}:80"
      - "{port-ssl}:443"
    volumes:
      - ./src:/var/www
      #- ./logs:/var/log/nginx
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      #- certbot-etc:/etc/letsencrypt
      #- certbot-var:/var/lib/letsencrypt
      #- ./docker/dhparam:/etc/ssl/certs
    depends_on:
      - ci4-app-{project}
    links:
      - mysql-{project}:db-server
    networks:
      - app-network-ci4-{project}
