
  sftp-{user}:
    image: atmoz/sftp
    restart: always
    volumes:
        - ./src:/home/{user}/uploads/{user}
    ports:
        - "{port}:22"
    command: {user}:{pass}:::uploads
    entrypoint: ["echo", "Service sftp-{user} disabled"]
