
  mysql-{project}:
    restart: always
    image: {version}
    ports:
      - {port}:3306
    volumes:
      - mysql_dir-{project}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: {pass}
    networks:
      - app-network-ci4-{project}
