version: '3'

services:

  # Docker compose way
#  docker-dood-milo:
#    restart: always
#    image: razzium/dind
#    container_name: docker-dood-milo
#    privileged: true
#    volumes:
#      - ${PWD}:/${PWD}
#      - "/var/run/docker.sock:/var/run/docker.sock"
#    working_dir: $PWD
#    tty: true

# Docker in docker -> todo PORTS mapping
# cmd ex : sudo docker exec docker-dind-milo bash -c 'cd envs;cd deploy_preprod_1;docker-compose up -d'
#  docker-dind-milo:
#    restart: always
#    image: razzium/dind
#    container_name: docker-dind-milo
#    privileged: true
#    volumes:
#      - ${PWD}:/${PWD}
#    ports:
#      - ??:80
#      - ??:3306
#    working_dir: $PWD
#    tty: true

  mariadb-milo:
    image: "mariadb"
    container_name: mariadb-milo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: oQ5x6dbx75eLhkpL
      MYSQL_ROOT_HOST: "%"
    ports:
      - "33060:3306"
    volumes:
      - mariadb-milo_dir:/var/lib/mysql
     # - ./image/mariadb:/docker-entrypoint-initdb.d TODO !!!
    expose:
      - "3306"

  php-milo:
    build: image/php
    container_name: php-milo
    restart: always
    depends_on:
      - mariadb-milo
    ports:
      - 9888:80
    links:
      - mariadb-milo:db-server
    volumes:
      - "..:/var/www/html"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  mariadb-milo_dir:
    driver: local