version: '2'

services:
  sftp-5cbf373cd3c91:
    image: atmoz/sftp
    restart: always
    volumes:
        - ./src:/home/5cbf373cd3c91
    ports:
        - "19122:22"
    command: 5cbf373cd3c91:FlPNGaDGqfLnShmw:::5cbf373cd3c91

  mysql-5cbf373cd3c91:
    restart: always
    image: mysql:5.5.58
    ports:
      - 14535:3306
    volumes:
      - mysql_dir-5cbf373cd3c91:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor

  php-5cbf373cd3c91:
    restart: always
    image: php:7.1-apache
    depends_on:
      - mysql-5cbf373cd3c91
    ports:
      - 15780:80
    links:
      - mysql-5cbf373cd3c91:db-server
    volumes:
      - "./src:/var/www/html"

volumes:
  mysql_dir-5cbf373cd3c91:
    driver: local
