version: '2'

services:
  mysql-5cbf08fed394c:
    restart: always
    image: mysql:5.5.58
    ports:
      - 11355:3306
    volumes:
      - mysql_dir-5cbf08fed394c:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor

  php-5cbf08fed394c:
    restart: always
    image: php:7.1-apache
    depends_on:
      - mysql-5cbf08fed394c
    ports:
      - 16800:80
    links:
      - mysql-5cbf08fed394c:db-server
    volumes:
      - "./src:/var/www/html"

volumes:
  mysql_dir-5cbf08fed394c:
    driver: local
