
version: '3'

services:
  mariadb-milo:
    image: "mariadb"
    environment:
      - MYSQL_ROOT_PASSWORD=oQ5x6dbx75eLhkpL
    ports:
      - "33060:3306"
    volumes:
      - mariadb-milo_dir:/var/lib/mysql
      - ./docker/mariadb:/docker-entrypoint-initdb.d
    expose:
      - "3306"

volumes:
  mariadb-milo_dir:
    driver: local