version: '2'

services:
  mysql-5cbf2f1306f5d:
    restart: always
    image: mysql:5.5.58
    ports:
      - 10453:3306
    volumes:
      - mysql_dir-5cbf2f1306f5d:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor

  php-5cbf2f1306f5d:
    restart: always
    image: php:7.1-apache
    depends_on:
      - mysql-5cbf2f1306f5d
    ports:
      - 22022:80
    links:
      - mysql-5cbf2f1306f5d:db-server
    volumes:
      - "./src:/var/www/html"

volumes:
  mysql_dir-5cbf2f1306f5d:
    driver: local
